# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f258f116ef355cca2ae62be6aa4b0b49fcce8159cde12ebdc028f7e7c0a3ea1d96eda588f0af11f462257d7b3be5667f1d1f013d497648085b6c65c02767231

test:
  secret_key_base: 63fb806f56107bd9d34b79c4d950ae0fc7c574e79f58a6fdf3c760250c50cec3203d8c01367c84461168dccef03c8820ca5d6df8d99df412ff3580b32cf4cf85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
